on: push

name: build

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc:
          - "8.10"
            # - "9.0"
            # - "9.2"
            # - "9.4"
        os:
          - ubuntu-latest
            # - macOS-latest
            # - windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Haskell
        id: setup-haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-

      - name: Make build plan
        run: cabal build all --dry-run

      - name: Build dependencies
        run: cabal build all --only-dependencies

      - name: Build local packages
        run: cabal build all

      - name: Test local packages
        run: cabal test all
